import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { PageHeader, StatGrid } from '../../components/PortalUI';
import { dashboardApi } from '../../services/api';

const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=value=>value?new Date(value).toLocaleDateString('pt-BR',{timeZone:'UTC'}):'A definir';
const labels={planning:'Planejamento',in_progress:'Em andamento',review:'Em revisão',completed:'Concluído',paused:'Pausado',requested:'Solicitado',analysis:'Em análise',quoted:'Aguardando você',approved:'Aprovado',rejected:'Recusado',cancelled:'Cancelado',open:'Aberto',waiting_client:'Aguardando você',resolved:'Resolvido',closed:'Encerrado',pending:'Pendente',paid:'Paga',overdue:'Vencida'};
const Empty=({children})=><div className="empty-state"><strong>Nada por aqui ainda</strong><span>{children}</span></div>;

export default function ClientHomePage(){
 const[data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{dashboardApi.client().then(setData).catch(e=>setError(e.message))},[]);
 if(!data)return <><PageHeader eyebrow="MINHA CONTA" title="Visão geral" description="Carregando as informações da sua conta."/>{error?<p className="auth-error">Não foi possível carregar sua visão geral: {error}</p>:<div className="users-loading">Organizando sua área...</div>}</>;
 const s=data.stats||{},projects=data.projects||[],orders=data.orders||[],tickets=data.tickets||[],invoices=data.invoices||[],firstName=(data.profile?.name||'Cliente').split(' ')[0];
 return <><PageHeader eyebrow="MINHA CONTA" title={`Olá, ${firstName}.`} description="Acompanhe seus projetos, solicitações, suporte e pagamentos em um só lugar."/><StatGrid items={[["Projetos ativos",s.activeProjects||0,`${s.averageProgress||0}% de progresso médio`],["Solicitações abertas",s.openOrders||0,`${s.quotedOrders||0} aguardando sua resposta`],["Tickets abertos",s.openTickets||0,`${s.waitingTickets||0} aguardando você`],["Faturas pendentes",s.pendingInvoices||0,money(s.pendingValue)]]}/>
 <div className="client-home-actions"><Link to="/cliente/projetos"><small>ENTREGAS</small><b>Acompanhar projetos</b><span>Veja etapas, progresso e prazos →</span></Link><Link to="/cliente/pedidos"><small>NOVA DEMANDA</small><b>Solicitar um serviço</b><span>Peça uma análise ou orçamento →</span></Link><Link to="/cliente/faturas"><small>FINANCEIRO</small><b>Consultar faturas</b><span>Acesse pagamentos e histórico →</span></Link><Link to="/cliente/suporte"><small>ATENDIMENTO</small><b>Falar com o suporte</b><span>Abra ou acompanhe uma conversa →</span></Link></div>
 <div className="admin-home-grid"><section className="panel portal-panel"><div className="panel-title"><div><h2>Meus projetos</h2><span>Últimas atualizações</span></div><Link to="/cliente/projetos">Ver todos</Link></div>{projects.length?projects.map(p=><div className="admin-project-line" key={p.id}><span className="user-identity"><b>{p.name}</b><small>{p.manager||'Equipe FiveSystem'} · Previsão {date(p.due_date)}</small></span><div><span>{labels[p.status]||p.status}</span><b>{p.progress}%</b><i><em style={{width:`${p.progress}%`}}/></i></div></div>):<Empty>Seus projetos aparecerão aqui quando forem iniciados.</Empty>}</section>
 <section className="panel portal-panel"><div className="panel-title"><div><h2>Financeiro</h2><span>Faturas recentes</span></div><Link to="/cliente/faturas">Ver todas</Link></div>{invoices.length?<div className="client-home-list">{invoices.map(i=><Link to="/cliente/faturas" key={i.id}><span><b>{i.code}</b><small>{i.description}</small></span><strong>{money(i.amount)}</strong><i className={`user-status ${i.status}`}>{labels[i.status]||i.status}</i><small>{date(i.due_date)}</small></Link>)}</div>:<Empty>Você não possui faturas no momento.</Empty>}</section></div>
 <div className="admin-home-grid lower"><section className="panel portal-panel"><div className="panel-title"><div><h2>Pedidos recentes</h2><span>Solicitações e propostas</span></div><Link to="/cliente/pedidos">Ver todos</Link></div>{orders.length?<div className="client-home-list">{orders.map(o=><Link to="/cliente/pedidos" key={o.id}><span><b>{o.code} · {o.title}</b><small>{o.estimated_value?money(o.estimated_value):'Proposta em preparação'}</small></span><i className={`user-status ${o.status}`}>{labels[o.status]||o.status}</i></Link>)}</div>:<Empty>Faça uma solicitação para começar um novo projeto.</Empty>}</section>
 <section className="panel portal-panel"><div className="panel-title"><div><h2>Suporte</h2><span>Conversas recentes</span></div><Link to="/cliente/suporte">Abrir central</Link></div>{tickets.length?<div className="client-home-list">{tickets.map(t=><Link to="/cliente/suporte" key={t.id}><span><b>{t.code} · {t.subject}</b><small>Atualizado em {date(t.updated_at)}</small></span><i className={`user-status ${t.status}`}>{labels[t.status]||t.status}</i></Link>)}</div>:<Empty>Você não possui tickets de suporte.</Empty>}</section></div></>;
}
