import { Route, Routes } from 'react-router-dom';
import DashboardLayout from '../../components/DashboardLayout';
import { FormPanel, PortalPage } from '../../components/PortalUI';

const configs = {
  home:{header:{eyebrow:'OPERAÇÃO',title:'Dashboard administrativo',description:'Visão geral da FiveSystem em tempo real.'},stats:[['Clientes ativos','128','+12 este mês'],['Projetos','24','18 em andamento'],['Tickets abertos','17','4 prioritários'],['Receita mensal','R$ 84k','+8,4% no período']],panel:{title:'Projetos em destaque',columns:['Projeto','Cliente','Status'],rows:[['Portal Commerce','Nexo Ltda.','Em andamento'],['App Operacional','Vértice SA','Em revisão'],['Automação CRM','Orbe Digital','Planejamento']]},secondary:{title:'Atividade',columns:['Evento','Horário'],rows:[['Novo cliente cadastrado','10:42'],['Projeto atualizado','09:18'],['Pagamento confirmado','Ontem']]}},
  usuarios:{header:{eyebrow:'ACESSOS',title:'Gerenciamento de usuários',description:'Controle contas, funções e permissões.',action:'Novo usuário'},stats:[['Usuários','156'],['Clientes','128'],['Equipe','22'],['Bloqueados','06']],panel:{title:'Usuários cadastrados',columns:['Usuário','Papel','Status'],rows:[['Marina Costa','client','Ativo'],['Carlos Lima','staff','Ativo'],['Ana Martins','admin','Ativo'],['João Alves','client','Bloqueado']]}},
  clientes:{header:{eyebrow:'RELACIONAMENTO',title:'Clientes',description:'Contas, contratos e saúde dos clientes.',action:'Novo cliente'},stats:[['Ativos','128'],['Novos no mês','12'],['Em onboarding','08'],['Inativos','14']],panel:{title:'Base de clientes',columns:['Cliente','Projetos','Status'],rows:[['Nexo Ltda.','03','Ativo'],['Vértice SA','02','Ativo'],['Orbe Digital','01','Onboarding'],['Nova Labs','00','Inativo']]}},
  projetos:{header:{eyebrow:'ENTREGAS',title:'Projetos',description:'Planejamento, responsáveis e andamento.',action:'Novo projeto'},stats:[['Total','42'],['Em andamento','18'],['Em revisão','06'],['Concluídos','18']],panel:{title:'Portfólio de projetos',columns:['Projeto','Responsável','Status'],rows:[['Portal Commerce','Lucas Rocha','72%'],['App Operacional','Bianca Melo','56%'],['Automação CRM','Rafael Dias','34%'],['ClientHub','Time Core','100%']]}},
  servicos:{header:{eyebrow:'CATÁLOGO',title:'Serviços',description:'Gerencie as soluções oferecidas pela FiveSystem.',action:'Novo serviço'},stats:[['Publicados','12'],['Rascunhos','03'],['Mais contratado','Sistemas'],['Conversão','18%']],panel:{title:'Catálogo',columns:['Serviço','Categoria','Status'],rows:[['Sistema sob medida','Desenvolvimento','Publicado'],['Automação de processos','Integração','Publicado'],['Consultoria técnica','Estratégia','Rascunho']]}},
  pedidos:{header:{eyebrow:'COMERCIAL',title:'Pedidos e orçamentos',description:'Acompanhe oportunidades e propostas.',action:'Novo orçamento'},stats:[['Em análise','14'],['Aguardando cliente','09'],['Aprovados','31'],['Conversão','42%']],panel:{title:'Pipeline comercial',columns:['Pedido','Cliente','Status'],rows:[['#1048','Nexo Ltda.','Em análise'],['#1047','Orbe Digital','Proposta enviada'],['#1046','Vértice SA','Aprovado'],['#1045','Nova Labs','Negociação']]}},
  tickets:{header:{eyebrow:'ATENDIMENTO',title:'Tickets de suporte',description:'Fila, prioridade e desempenho do suporte.',action:'Novo ticket'},stats:[['Abertos','17'],['Prioritários','04'],['Tempo médio','2h 12m'],['Satisfação','96%']],panel:{title:'Fila de atendimento',columns:['Ticket','Cliente','Status'],rows:[['#024','Nexo Ltda.','Prioritário'],['#023','Vértice SA','Em atendimento'],['#022','Orbe Digital','Aguardando cliente'],['#021','Nova Labs','Novo']]}},
  conteudo:{header:{eyebrow:'SITE',title:'Gerenciamento de conteúdo',description:'Organize textos, projetos e materiais públicos.',action:'Novo conteúdo'},stats:[['Publicados','36'],['Rascunhos','05'],['Agendados','02'],['Atualizados hoje','04']],panel:{title:'Conteúdos recentes',columns:['Conteúdo','Área','Status'],rows:[['Case FiveCommerce','Projetos','Publicado'],['Integrações inteligentes','Serviços','Rascunho'],['FAQ de suporte','Ajuda','Publicado']]}},
  metricas:{header:{eyebrow:'ANÁLISE',title:'Métricas',description:'Indicadores de operação, produto e crescimento.'},stats:[['Visitantes','18,4k','+14%'],['Conversões','327','+8%'],['MRR','R$ 84k','+8,4%'],['Retenção','94%','+2%']],panel:{title:'Desempenho mensal',columns:['Indicador','Atual','Variação'],rows:[['Novos leads','482','+18%'],['Propostas enviadas','68','+11%'],['Projetos fechados','21','+7%'],['Tickets resolvidos','194','+22%']]}},
  logs:{header:{eyebrow:'AUDITORIA',title:'Logs e atividade',description:'Histórico das ações realizadas no sistema.'},panel:{title:'Eventos recentes',columns:['Ação','Responsável','Data'],rows:[['Permissão de usuário alterada','Ana Martins','Hoje, 10:32'],['Projeto #042 atualizado','Lucas Rocha','Hoje, 09:18'],['Cliente bloqueado','Carlos Lima','Ontem, 17:44'],['Conteúdo publicado','Bianca Melo','Ontem, 15:20']]}},
};

function AdminSettings(){return <><div className="portal-head"><div><small>SISTEMA</small><h1 className="display">Configurações</h1><p>Preferências gerais e identidade da plataforma.</p></div></div><FormPanel title="Configurações gerais" fields={[["Nome da empresa","FiveSystem"],["E-mail de suporte","suporte@fivesystem.com.br","email"],["URL pública","https://fivesystem.com.br"]]}/></>}

export default function AdminDashboard(){return <DashboardLayout admin><Routes>
  <Route index element={<PortalPage config={configs.home}/>}/>
  {Object.entries(configs).filter(([key])=>key!=='home').map(([path,config])=><Route key={path} path={path} element={<PortalPage config={config}/>}/>)}
  <Route path="configuracoes" element={<AdminSettings/>}/><Route path="*" element={<PortalPage config={configs.home}/>}/>
</Routes></DashboardLayout>}
