import { useEffect, useState } from 'react';
import { PageHeader, StatGrid } from '../../components/PortalUI';
import { clientsApi, projectsApi } from '../../services/api';

const emptyProject={name:'',clientId:'',description:'',category:'Desenvolvimento',manager:'',status:'planning',priority:'medium',progress:0,startDate:'',dueDate:'',budget:0};
export default function ProjectsPage(){
 const[projects,setProjects]=useState([]),[clients,setClients]=useState([]),[stats,setStats]=useState({total:0,inProgress:0,inReview:0,completed:0});
 const[search,setSearch]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[removeTarget,setRemoveTarget]=useState(null),[form,setForm]=useState(emptyProject),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[updating,setUpdating]=useState(null);
 async function load(filters){setLoading(true);try{const[data,clientData]=await Promise.all([projectsApi.list(filters),clientsApi.list({limit:100})]);setProjects(data.projects);setStats(data.stats);setClients(clientData.clients);}catch(e){setError(e.message);}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const update=e=>setForm(f=>({...f,[e.target.name]:e.target.value}));
 const openCreate=()=>{setEditing(null);setForm({...emptyProject,clientId:clients[0]?.id||''});setError('');setModal(true)};
 const openEdit=p=>{setEditing(p);setForm({name:p.name,clientId:p.clientId,description:p.description,category:p.category,manager:p.manager,status:p.status,priority:p.priority,progress:p.progress,startDate:p.startDate?.slice?.(0,10)||'',dueDate:p.dueDate?.slice?.(0,10)||'',budget:p.budget});setError('');setModal(true)};
 const close=()=>{setModal(false);setEditing(null);setError('')};
 async function submit(e){e.preventDefault();setSaving(true);setError('');try{editing?await projectsApi.update(editing.id,form):await projectsApi.create(form);close();await load(search?{search}:undefined);}catch(err){setError(err.message)}finally{setSaving(false)}}
 async function remove(){setSaving(true);setError('');try{await projectsApi.remove(removeTarget.id);setRemoveTarget(null);await load(search?{search}:undefined)}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function quickUpdate(project,changes){setUpdating(project.id);setError('');try{const{project:updated}=await projectsApi.update(project.id,changes);setProjects(current=>current.map(item=>item.id===updated.id?updated:item));const data=await projectsApi.list(search?{search}:undefined);setStats(data.stats)}catch(e){setError(e.message)}finally{setUpdating(null)}}
 const status={planning:'Planejamento',in_progress:'Em andamento',review:'Em revisão',completed:'Concluído',paused:'Pausado',cancelled:'Cancelado'};
 return <><PageHeader eyebrow="ENTREGAS" title="Projetos" description="Planejamento, prazos, clientes e andamento das entregas." action="Novo projeto" onAction={openCreate}/><StatGrid items={[["Total",stats.total],["Em andamento",stats.inProgress],["Em revisão",stats.inReview],["Concluídos",stats.completed]]}/>
 <div className="portal-single"><section className="panel portal-panel users-panel"><div className="clients-toolbar"><div><h2>Portfólio de projetos</h2><span>{projects.length} projetos exibidos · alterações rápidas são salvas automaticamente</span></div><form onSubmit={e=>{e.preventDefault();load(search?{search}:undefined)}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar projeto ou cliente"/><button>Buscar</button></form></div>{error&&!modal&&!removeTarget&&<p className="auth-error">{error}</p>}{loading?<div className="users-loading">Carregando projetos...</div>:<div className="users-table"><div className="projects-row users-head"><span>Projeto</span><span>Cliente</span><span>Progresso</span><span>Status</span><span>Ações</span></div>{projects.map(p=><div className={`projects-row ${updating===p.id?'is-updating':''}`} key={p.id}><span className="user-identity"><b>{p.name}</b><small>{p.category} · {p.priority}</small></span><span>{p.clientName}</span><span><div className="quick-progress"><button disabled={updating===p.id||p.progress===0} onClick={()=>quickUpdate(p,{progress:Math.max(0,p.progress-10)})}>−</button><div className="project-progress"><i style={{width:`${p.progress}%`}}/><b>{p.progress}%</b></div><button disabled={updating===p.id||p.progress===100} onClick={()=>quickUpdate(p,{progress:Math.min(100,p.progress+10)})}>＋</button></div></span><span><select className={`quick-status ${p.status}`} disabled={updating===p.id} value={p.status} onChange={e=>quickUpdate(p,{status:e.target.value})}>{Object.entries(status).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></span><span className="user-actions"><button onClick={()=>openEdit(p)}>Editar</button><button className="danger" onClick={()=>{setError('');setRemoveTarget(p)}}>Remover</button></span></div>)}</div>}</section></div>
 {modal&&<div className="user-modal-backdrop"><section className="user-modal project-modal"><button className="user-modal-close" onClick={close}>×</button><span className="login-context">{editing?'EDITAR PROJETO':'NOVO PROJETO'}</span><h2 className="display">{editing?'Editar projeto':'Criar projeto'}</h2><p>Organize o escopo e o acompanhamento da entrega.</p><form onSubmit={submit}><div className="client-modal-grid"><label><span>NOME DO PROJETO</span><input autoFocus required name="name" value={form.name} onChange={update}/></label><label><span>CLIENTE</span><select required name="clientId" value={form.clientId} onChange={update}><option value="">Selecione</option>{clients.map(c=><option value={c.id} key={c.id}>{c.company||c.name}</option>)}</select></label><label><span>CATEGORIA</span><input name="category" value={form.category} onChange={update}/></label><label><span>RESPONSÁVEL</span><input name="manager" value={form.manager} onChange={update}/></label><label><span>STATUS</span><select name="status" value={form.status} onChange={update}>{Object.entries(status).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label><span>PRIORIDADE</span><select name="priority" value={form.priority} onChange={update}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label className="project-range-field"><span>PROGRESSO DO PROJETO <b>{form.progress}%</b></span><input type="range" min="0" max="100" step="5" name="progress" value={form.progress} onChange={update}/><div className="progress-presets">{[0,25,50,75,100].map(value=><button type="button" className={Number(form.progress)===value?'active':''} onClick={()=>setForm(f=>({...f,progress:value}))} key={value}>{value}%</button>)}</div></label><label><span>ORÇAMENTO (R$)</span><input type="number" min="0" step="0.01" name="budget" value={form.budget} onChange={update}/></label><label><span>INÍCIO</span><input type="date" name="startDate" value={form.startDate} onChange={update}/></label><label><span>PREVISÃO DE ENTREGA</span><input type="date" name="dueDate" value={form.dueDate} onChange={update}/></label><label className="client-notes"><span>DESCRIÇÃO</span><textarea name="description" value={form.description} onChange={update} rows="4"/></label></div>{error&&<p className="auth-error">{error}</p>}<div className="user-modal-actions"><button type="button" className="btn btn-secondary" onClick={close}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving?'Salvando...':editing?'Salvar alterações':'Criar projeto'}</button></div></form></section></div>}
 {removeTarget&&<div className="user-modal-backdrop"><section className="user-modal confirm-user-delete"><button className="user-modal-close" onClick={()=>setRemoveTarget(null)}>×</button><span className="login-context danger-text">AÇÃO IRREVERSÍVEL</span><h2 className="display">Remover projeto?</h2><p>O projeto <strong>{removeTarget.name}</strong> será removido.</p>{error&&<p className="auth-error">{error}</p>}<div className="user-modal-actions"><button className="btn btn-secondary" onClick={()=>setRemoveTarget(null)}>Cancelar</button><button className="btn btn-danger" disabled={saving} onClick={remove}>{saving?'Removendo...':'Remover projeto'}</button></div></section></div>}</>;
}
