import{useEffect,useState}from'react';
import{PageHeader,StatGrid}from'../../components/PortalUI';
import{servicesApi}from'../../services/api';
const empty={name:'',category:'Desenvolvimento',shortDescription:'',description:'',priceFrom:0,deliveryDays:30,status:'published',featured:false,sortOrder:0};
export default function ServicesPage(){
 const[services,setServices]=useState([]),[stats,setStats]=useState({total:0,published:0,drafts:0,featured:0}),[search,setSearch]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[removeTarget,setRemoveTarget]=useState(null),[form,setForm]=useState(empty),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[updating,setUpdating]=useState(null);
 async function load(filters){setLoading(true);try{const d=await servicesApi.list(filters);setServices(d.services);setStats(d.stats)}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 const update=e=>setForm(f=>({...f,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}));
 const openCreate=()=>{setEditing(null);setForm(empty);setError('');setModal(true)},openEdit=s=>{setEditing(s);setForm({...s});setError('');setModal(true)},close=()=>{setModal(false);setEditing(null);setError('')};
 async function submit(e){e.preventDefault();setSaving(true);setError('');try{editing?await servicesApi.update(editing.id,form):await servicesApi.create(form);close();await load(search?{search}:undefined)}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function quickUpdate(service,changes){setUpdating(service.id);try{const{service:changed}=await servicesApi.update(service.id,changes);setServices(a=>a.map(x=>x.id===changed.id?changed:x));const d=await servicesApi.list(search?{search}:undefined);setStats(d.stats)}catch(e){setError(e.message)}finally{setUpdating(null)}}
 async function remove(){setSaving(true);try{await servicesApi.remove(removeTarget.id);setRemoveTarget(null);await load(search?{search}:undefined)}catch(e){setError(e.message)}finally{setSaving(false)}}
 const labels={draft:'Rascunho',published:'Publicado',archived:'Arquivado'};const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <><PageHeader eyebrow="CATÁLOGO" title="Serviços" description="Gerencie o catálogo de soluções oferecidas pela FiveSystem." action="Novo serviço" onAction={openCreate}/><StatGrid items={[["Total",stats.total],["Publicados",stats.published],["Rascunhos",stats.drafts],["Em destaque",stats.featured]]}/><div className="portal-single"><section className="panel portal-panel users-panel"><div className="clients-toolbar"><div><h2>Catálogo de serviços</h2><span>{services.length} serviços exibidos · publicação rápida</span></div><form onSubmit={e=>{e.preventDefault();load(search?{search}:undefined)}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar serviço ou categoria"/><button>Buscar</button></form></div>{error&&!modal&&!removeTarget&&<p className="auth-error">{error}</p>}{loading?<div className="users-loading">Carregando serviços...</div>:<div className="users-table"><div className="services-row users-head"><span>Serviço</span><span>Valor inicial</span><span>Prazo</span><span>Status</span><span>Ações</span></div>{services.map(s=><div className={`services-row ${updating===s.id?'is-updating':''}`} key={s.id}><span className="user-identity"><b>{s.name}{s.featured&&<em className="featured-mark">Destaque</em>}</b><small>{s.category} · /{s.slug}</small></span><span>{money(s.priceFrom)}</span><span>{s.deliveryDays} dias</span><span><select className={`quick-status ${s.status}`} value={s.status} disabled={updating===s.id} onChange={e=>quickUpdate(s,{status:e.target.value})}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></span><span className="user-actions"><button onClick={()=>openEdit(s)}>Editar</button><button className="danger" onClick={()=>{setError('');setRemoveTarget(s)}}>Remover</button></span></div>)}</div>}</section></div>
 {modal&&<div className="user-modal-backdrop"><section className="user-modal service-modal"><button className="user-modal-close" onClick={close}>×</button><span className="login-context">{editing?'EDITAR SERVIÇO':'NOVO SERVIÇO'}</span><h2 className="display">{editing?'Editar serviço':'Criar serviço'}</h2><p>Defina como esta solução será apresentada e comercializada.</p><form onSubmit={submit}><div className="client-modal-grid"><label><span>NOME</span><input autoFocus required name="name" value={form.name} onChange={update}/></label><label><span>CATEGORIA</span><input required name="category" value={form.category} onChange={update}/></label><label className="client-notes"><span>RESUMO</span><input required minLength="10" name="shortDescription" value={form.shortDescription} onChange={update} placeholder="Descrição curta para cartões e listagens"/></label><label><span>VALOR A PARTIR DE (R$)</span><input type="number" min="0" step="0.01" name="priceFrom" value={form.priceFrom} onChange={update}/></label><label><span>PRAZO ESTIMADO (DIAS)</span><input type="number" min="1" name="deliveryDays" value={form.deliveryDays} onChange={update}/></label><label><span>STATUS</span><select name="status" value={form.status} onChange={update}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label><span>ORDEM DE EXIBIÇÃO</span><input type="number" min="0" name="sortOrder" value={form.sortOrder} onChange={update}/></label><label className="service-featured"><input type="checkbox" name="featured" checked={form.featured} onChange={update}/><span>Destacar este serviço no catálogo</span></label><label className="client-notes"><span>DESCRIÇÃO COMPLETA</span><textarea name="description" value={form.description} onChange={update} rows="5"/></label></div>{error&&<p className="auth-error">{error}</p>}<div className="user-modal-actions"><button type="button" className="btn btn-secondary" onClick={close}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving?'Salvando...':editing?'Salvar alterações':'Criar serviço'}</button></div></form></section></div>}
 {removeTarget&&<div className="user-modal-backdrop"><section className="user-modal confirm-user-delete"><button className="user-modal-close" onClick={()=>setRemoveTarget(null)}>×</button><span className="login-context danger-text">AÇÃO IRREVERSÍVEL</span><h2 className="display">Remover serviço?</h2><p><strong>{removeTarget.name}</strong> será removido do catálogo.</p>{error&&<p className="auth-error">{error}</p>}<div className="user-modal-actions"><button className="btn btn-secondary" onClick={()=>setRemoveTarget(null)}>Cancelar</button><button className="btn btn-danger" disabled={saving} onClick={remove}>{saving?'Removendo...':'Remover serviço'}</button></div></section></div>}</>;
}
