import { useEffect, useState } from 'react';
import { PageHeader } from '../../components/PortalUI';
import { settingsApi } from '../../services/api';

const initial={companyName:'',supportEmail:'',supportPhone:'',businessHours:'',timezone:'America/Sao_Paulo',defaultTicketPriority:'medium',notifyNewClient:true,notifyNewOrder:true,notifyNewTicket:true,maintenanceMode:false,maintenanceMessage:'Estamos realizando melhorias importantes para deixar a plataforma mais segura, rápida e estável. Voltaremos em breve.'};
function Switch({name,label,text,checked,onChange,danger}){return <label className={`settings-switch ${danger?'danger':''}`}><span><b>{label}</b><small>{text}</small></span><input type="checkbox" name={name} checked={checked} onChange={onChange}/><i/></label>}
export default function SettingsPage(){
  const[form,setForm]=useState(initial),[saved,setSaved]=useState(initial),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  useEffect(()=>{settingsApi.get().then(d=>{setForm(d.settings);setSaved(d.settings)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
  const dirty=JSON.stringify(form)!==JSON.stringify(saved);
  const update=e=>{setMessage('');setForm(f=>({...f,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}))};
  async function save(e){e.preventDefault();setSaving(true);setError('');setMessage('');try{const d=await settingsApi.update(form);setForm(d.settings);setSaved(d.settings);if(d.maintenanceActivated)return window.location.reload();setMessage('Configurações salvas com sucesso.')}catch(e){setError(e.message)}finally{setSaving(false)}}
  return <><PageHeader eyebrow="SISTEMA" title="Configurações" description="Identidade, atendimento e preferências operacionais da FiveSystem."/>{loading?<div className="users-loading">Carregando configurações...</div>:<form className="settings-page" onSubmit={save}>
    <section className="panel portal-panel settings-section"><div className="panel-title"><div><h2>Empresa e atendimento</h2><span>Informações usadas pela equipe nos contatos com clientes</span></div></div><div className="settings-fields"><label><span>NOME DA EMPRESA</span><input required name="companyName" value={form.companyName} onChange={update}/></label><label><span>E-MAIL DE SUPORTE</span><input required type="email" name="supportEmail" value={form.supportEmail} onChange={update}/></label><label><span>TELEFONE / WHATSAPP</span><input name="supportPhone" value={form.supportPhone} onChange={update}/></label><label><span>HORÁRIO DE ATENDIMENTO</span><input name="businessHours" value={form.businessHours} onChange={update}/></label></div></section>
    <section className="panel portal-panel settings-section"><div className="panel-title"><div><h2>Operação</h2><span>Padrões utilizados nas rotinas internas</span></div></div><div className="settings-fields"><label><span>FUSO HORÁRIO</span><select name="timezone" value={form.timezone} onChange={update}><option value="America/Sao_Paulo">Brasília / São Paulo</option><option value="America/Manaus">Manaus</option><option value="America/Recife">Recife</option><option value="America/Fortaleza">Fortaleza</option></select></label><label><span>PRIORIDADE PADRÃO DE TICKET</span><select name="defaultTicketPriority" value={form.defaultTicketPriority} onChange={update}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></label></div></section>
    <section className="panel portal-panel settings-section"><div className="panel-title"><div><h2>Notificações internas</h2><span>Eventos que devem chamar a atenção da equipe</span></div></div><div className="settings-switches"><Switch name="notifyNewClient" label="Novo cliente" text="Avisar quando uma conta de cliente for criada" checked={form.notifyNewClient} onChange={update}/><Switch name="notifyNewOrder" label="Novo pedido" text="Avisar quando chegar uma solicitação" checked={form.notifyNewOrder} onChange={update}/><Switch name="notifyNewTicket" label="Novo ticket" text="Avisar quando um cliente solicitar suporte" checked={form.notifyNewTicket} onChange={update}/></div></section>
    <section className="panel portal-panel settings-section danger-zone"><div className="panel-title"><div><h2>Disponibilidade do sistema</h2><span>Ao ativar, todo o site será bloqueado imediatamente</span></div></div><label className="maintenance-reason"><span>MENSAGEM EXIBIDA AOS VISITANTES</span><textarea required minLength="10" maxLength="500" rows="4" name="maintenanceMessage" value={form.maintenanceMessage} onChange={update}/></label><Switch danger name="maintenanceMode" label="Ativar modo de manutenção" text="Um código único será gerado exclusivamente no console do servidor" checked={form.maintenanceMode} onChange={update}/></section>
    {error&&<p className="auth-error">{error}</p>}{message&&<p className="settings-success">{message}</p>}{dirty&&<div className="settings-save"><span>Existem alterações que ainda não foram salvas.</span><button className="btn btn-primary" disabled={saving}>{saving?'Salvando...':form.maintenanceMode?'Salvar e bloquear o site':'Salvar alterações'}</button></div>}
  </form>}</>;
}
